# Generated by Django 4.2.1 on 2023-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='groupPic',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='groupName',
            field=models.CharField(max_length=64),
        ),
    ]
