# Generated by Django 4.2.1 on 2023-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempApp', '0002_catalog_grouppic_alter_catalog_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='groupPic',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
