# Generated by Django 4.2.1 on 2023-05-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dempApp', '0003_alter_catalog_grouppic'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailName', models.CharField(max_length=64)),
                ('detailPic', models.ImageField(default=None, upload_to='detail/')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dempApp.catalog')),
            ],
        ),
    ]
